apiVersion: v1
kind: Service
metadata:
  name: {{ include "safe.fullname" . }}
  namespace: {{ .Values.global.aegis.namespace }}
  labels:
    {{- include "safe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "safe.selectorLabels" . | nindent 4 }}
