# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: default
  labels:
    app.kubernetes.io/name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example
    spec:
      serviceAccountName: example
      containers:
      - name: main
        image: vsecm/example-using-init-container:latest

        volumeMounts:
        # Share with Sidecar. When the `main` container is ready,
        # this volume will be populated with the secret that the
        # `main` container needs.
        - mountPath: /opt/vsecm
          name: vsecm-secrets-volume

        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: vsecm-secret-example
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: vsecm-secret-example
              key: password
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: vsecm-secret-example
              key: secret

      # `main` shares this volume with `sidecar`.
      - name: sidecar
        image: vsecm/vsecm-ist-sidecar:latest
        volumeMounts:
          # /opt/vsecm/secrets.json is the place the secrets will be at.
          # The main application can read the secrets from this location too.
          - mountPath: /opt/vsecm
            name: vsecm-secrets-volume
          # Volume mount for SPIRE unix domain socket.
          - name: spire-agent-socket
            mountPath: /spire-agent-socket
            readOnly: true

        #
        # You can configure this workload by providing environment variables.
        #
        # See https://vsecm.com/configuration for more information about
        # these environment variables.
        #
        # When you don't explicitly provide env vars here, VMware Secrets Manager
        # Safe will assume the default values outlined in the given link above.
        #
        env:
          - name: SPIFFE_ENDPOINT_SOCKET
            value: "unix:///spire-agent-socket/spire-agent.sock"
          - name: VSECM_LOG_LEVEL
            value: "7"
          - name: VSECM_SPIFFEID_PREFIX_WORKLOAD
            value: "spiffe://vsecm.com/workload/"
          - name: VSECM_SPIFFEID_PREFIX_SAFE
            value: "spiffe://vsecm.com/workload/vsecm-safe/ns/vsecm-system/sa/vsecm-safe/n/"
          - name: VSECM_SIDECAR_POLL_INTERVAL
            value: "5000"
          - name: VSECM_SIDECAR_MAX_POLL_INTERVAL
            value: "300000"
          - name: VSECM_SIDECAR_EXPONENTIAL_BACKOFF_MULTIPLIER
            value: "2"
          - name: VSECM_SIDECAR_SUCCESS_THRESHOLD
            value: "3"
          - name: VSECM_SIDECAR_ERROR_THRESHOLD
            value: "2"

      initContainers:
      # See `./register.sh` to register the workload and finalize
      # this init container.
      - name: init-container
        image: vsecm/vsecm-ist-init-container:latest
        volumeMounts:
        # Volume mount for SPIRE unix domain socket.
        - name: spire-agent-socket
          mountPath: /spire-agent-socket
          readOnly: true
        #
        # You can configure VSecM Init Container by providing
        # environment variables.
        #
        # See https://vsecm.com/configuration for more information
        # about these environment variables.
        #
        # When you don't explicitly provide env vars here, VMware Secrets Manager
        # Init Container will assume the default values outlined in the given
        # link above.
        #
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///spire-agent-socket/spire-agent.sock"
        - name: VSECM_LOG_LEVEL
          value: "7"
        - name: VSECM_SPIFFEID_PREFIX_WORKLOAD
          value: "spiffe://vsecm.com/workload/"
        - name: VSECM_SPIFFEID_PREFIX_SAFE
          value: "spiffe://vsecm.com/workload/vsecm-safe/ns/vsecm-system/sa/vsecm-safe/n/"
        - name: VSECM_INIT_CONTAINER_POLL_INTERVAL
          value: "5000"
      volumes:
      # Using SPIFFE CSI Driver to bind to the SPIRE Agent Socket
      # ref: https://github.com/spiffe/spiffe-csi
      - name: spire-agent-socket
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
      # A memory-backed volume is recommended (but not required) to keep
      # the secrets. The secrets can be stored in any kind of volume.
      - name: vsecm-secrets-volume
        emptyDir:
          medium: Memory
