apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: webhook-backend
spec:
  provider:
    webhook:
      url: "http://eso-webhook.default.svc.cluster.local:80/webhook?key={{ .remoteRef.key }}"
      method: GET
      result:
        jsonPath: "$"