apiVersion: v1
kind: Secret
metadata:
  name: vsecm-sentinel-init-secret
  namespace: vsecm-system
type: Opaque
stringData:
  data: |
    w:"k8s:keycloak-admin-secret"
    n:"smo-app"
    s:'gen:{"username":"admin-[a-z0-9]{6}","password":"[a-zA-Z0-9]{12}"}'
    t:'{"KEYCLOAK_ADMIN_USER":"{{.username}}","KEYCLOAK_ADMIN_PASSWORD":"{{.password}}"}'
    --
    w:"k8s:keycloak-db-secret"
    n:"smo-app"
    s:'gen:{"username":"admin-[a-z0-9]{6}","password":"[a-zA-Z0-9]{12}"}'
    t:'{"KEYCLOAK_DB_USER":"{{.username}}","KEYCLOAK_DB_PASSWORD":"{{.password}}"}'
    --
    sleep:5000
    --
    w:keycloak
    n:default
    s:trigger-init
    --
