
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: "csi.spiffe.io"
  annotations:
    "helm.sh/hook": pre-install
spec:
  attachRequired: false

  podInfoOnMount: true

  fsGroupPolicy: None

  volumeLifecycleModes: # added in Kubernetes 1.16, this field is beta
    - Ephemeral
