
apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire-server
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: spire-server
