# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: {{ .Values.global.vsecm.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sentinel.serviceAccountName" . }}
    namespace: {{ .Values.global.vsecm.namespace }}
roleRef:
  kind: Role
  name: vsecm-sentinel-secret-reader
  apiGroup: rbac.authorization.k8s.io