# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

# ServiceAccount used by the SPIRE server.
apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: {{ .Values.global.spire.serverNamespace }}
  labels:
    {{- include "spire.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.global.spire.serverPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    app: spire-server
