# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

# Binds above cluster role to spire-server service account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spire-server-spire-server
  labels:
    {{- include "spire.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: spire-server
    namespace: {{ .Values.global.spire.serverNamespace }}
roleRef:
  kind: ClusterRole
  name: spire-server-spire-server
  apiGroup: rbac.authorization.k8s.io
