# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: main
        image: public.ecr.aws/h8y1n7y7/example-using-init-container:0.24.5
      initContainers:
      - name: init-container
        image: public.ecr.aws/h8y1n7y7/vsecm-ist-init-container:0.24.5
