apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: vsecm-safe
spec:
  spiffeIDTemplate: "spiffe://cluster2.demo\
    /workload/vsecm-safe\
    /ns/{{ .PodMeta.Namespace }}\
    /sa/{{ .PodSpec.ServiceAccountName }}\
    /n/{{ .PodMeta.Name }}"
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vsecm-safe
      app.kubernetes.io/part-of: vsecm-system
  workloadSelectorTemplates:
  - "k8s:ns:vsecm-system"
  - "k8s:sa:vsecm-safe"
