# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: v1
kind: Service
metadata:
  name: vsecm-safe
  namespace: vsecm-system
  labels:
    app.kubernetes.io/name: vsecm-safe
    app.kubernetes.io/part-of: vsecm-system
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: vsecm-safe
    app.kubernetes.io/part-of: vsecm-system
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
