# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - Deployment.yaml
patches:
  - path: image-override-photon-local.yaml
generatorOptions:
  disableNameSuffixHash: true
