# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: {{ include "keystone.fullname" . }}
  labels:
    {{- include "keystone.labels" . | nindent 4 }}
spec:
  className: {{ .Values.global.spire.controllerManagerClassName | quote }}
  spiffeIDTemplate: {{ .Values.global.vsecm.keystoneSpiffeIdTemplate }}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "keystone.fullname" . }}
      app.kubernetes.io/part-of: {{ .Values.global.vsecm.namespace }}
  workloadSelectorTemplates:
    - "k8s:ns:{{ .Values.global.vsecm.namespace }}"
    - "k8s:sa:{{ include "keystone.serviceAccountName" . }}"
