# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-controller-manager
  namespace: {{ .Values.global.spire.serverNamespace }}
data:
  controller-manager-config.yaml: |
    
    apiVersion: spire.spiffe.io/v1alpha1
    kind: ControllerManagerConfig
    metadata:
      name: spire-controller-manager
      namespace: {{ .Values.global.spire.serverNamespace }}
      labels:
        helm.sh/chart: {{ include "spire.chart" . }}
        app.kubernetes.io/name: server
        app.kubernetes.io/instance: spire
        app.kubernetes.io/version: "1.9.6"
        app.kubernetes.io/managed-by: Helm
    metrics:
      bindAddress: 0.0.0.0:8082
    health:
      healthProbeBindAddress: 0.0.0.0:8083
    leaderElection:
      leaderElect: true
      resourceName: 6f304bd2.spiffe.io
      resourceNamespace: {{ .Values.global.spire.serverNamespace }}
    validatingWebhookConfigurationName: spire-server-spire-controller-manager-webhook
    entryIDPrefix: vsecm-cluster
    clusterName: vsecm-cluster
    trustDomain: vsecm.com
    ignoreNamespaces:
      - kube-system
      - kube-public
      - local-path-storage
      - openshift-cluster-node-tuning-operator
      - openshift-cluster-samples-operator
      - openshift-cluster-storage-operator
      - openshift-console-operator
      - openshift-console
      - openshift-dns
      - openshift-dns-operator
      - openshift-image-registry
      - openshift-ingress
      - openshift-kube-storage-version-migrator
      - openshift-kube-storage-version-migrator-operator
      - openshift-kube-proxy
      - openshift-marketplace
      - openshift-monitoring
      - openshift-multus
      - openshift-network-diagnostics
      - openshift-network-operator
      - openshift-operator-lifecycle-manager
      - openshift-roks-metrics
      - openshift-service-ca-operator
      - openshift-service-ca
      - ibm-odf-validation-webhook
      - ibm-system
    spireServerSocketPath: "{{ .Values.spireServer.privateSocketDir }}/api.sock"
    className: {{ .Values.global.spire.controllerManagerClassName | quote }}
    watchClassless: false
    parentIDTemplate: "spiffe://{{"{{"}} .TrustDomain {{"}}"}}/spire/agent/k8s_psat/{{"{{"}} .ClusterName {{"}}"}}/{{"{{"}} .NodeMeta.UID {{"}}"}}"
    reconcile:
      clusterSPIFFEIDs: true
      clusterStaticEntries: true
      clusterFederatedTrustDomains: true
