# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

{{- if .Values.global.useClusterSpiffeIds }}

apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: {{ include "sentinel.fullname" . }}
spec:
  spiffeIDTemplate: {{ .Values.global.vsecm.sentinelSpiffeIdTemplate }}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sentinel.fullname" . }}
      app.kubernetes.io/part-of: {{ .Values.global.vsecm.namespace }}
  workloadSelectorTemplates:
    - "k8s:ns:{{ .Values.global.vsecm.namespace }}"
    - "k8s:sa:{{ include "sentinel.serviceAccountName" . }}"

{{- end }}
