# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

# Default values for keystone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

livenessPort: 8081

# -- See https://vsecm.com/configuration for more information
# about these environment variables.
environments:
  # -- The log level. 0: Logs are off (only audit events will be logged)
  # 7: TRACE level logging (maximum verbosity).
  - name: VSECM_LOG_LEVEL
    value: "7"

# -- See https://vsecm.com/configuration for more information
# about these environment variables.
initEnvironments:
  # -- The SPIFFE endpoint socket. This is used to communicate with the SPIRE 
  # agent. If you change this, you will need to change the associated 
  # volumeMount in the Deployment.yaml too.
  - name: SPIFFE_ENDPOINT_SOCKET
    value: "unix:///spire-agent-socket/agent.sock"
  # -- The log level. 0: Logs are off (only audit events will be logged)
  # 7: TRACE level logging (maximum verbosity).
  - name: VSECM_LOG_LEVEL
    value: "7"
  # -- The interval (in milliseconds) that the VSecM Init Container will poll
  # the VSecM Safe for secrets.
  - name: VSECM_INIT_CONTAINER_POLL_INTERVAL
    value: "5000"

# -- Override it with an image pull secret that you need as follows:
# imagePullSecrets:
#  - name: my-registry-secret
imagePullSecrets: []

# -- The name override of the chart.
nameOverride: ""
# -- The fullname override of the chart.
fullnameOverride: ""

# -- The service account to use.
serviceAccount:
  # -- Specifies whether a service account should be created.
  create: true
  # -- Annotations to add to the service account.
  annotations: {}
  # -- The name of the service account to use.
  # If not set and 'create' is true, a name is generated using the fullname
  # template.
  name: "vsecm-keystone"

# -- Additional pod annotations.
podAnnotations: {}

# -- Pod security context overrides.
podSecurityContext: {}
# fsGroup: 2000

# -- Resource limits and requests.
resources:
  # These are default requests that can be used as a starting point.
  # Of course, benchmark your production system to determine the actual
  # requests you need.
  requests:
    memory: "20Mi"
    cpu: "5m"

# -- Autoscaling settings. Note that, by default, autoscaling is disabled.
# It does not typically make sense to autoscale VSecM Keystone as it is
# a control plane component with minimal resource requirements.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
