/*
|    Protect your secrets, protect your sensitive data.
:    Explore VMware Secrets Manager docs at https://vsecm.com/
</
<>/  keep your secrets... secret
>/
<>/' Copyright 2023-present VMware Secrets Manager contributors.
>/'  SPDX-License-Identifier: BSD-2-Clause
*/

package val

// JsonEmpty is a constant string representing an empty value.
// This value is generated by the go templating engine
// when a key-value pair has no value. Don't change this value.
const JsonEmpty = "<no value>"
