kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spire-server-post-install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
subjects:
  - kind: ServiceAccount
    name: spire-server-post-install
    namespace: spire-server
roleRef:
  kind: ClusterRole
  name: spire-server-post-install
  apiGroup: rbac.authorization.k8s.io
