apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-agent
  namespace: spire-system
  labels:
    helm.sh/chart: spire-agent-0.1.0
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: spire
    app.kubernetes.io/version: "1.9.6"
    app.kubernetes.io/managed-by: Helm
