{{- if .Values.initCommand.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: vsecm-sentinel-init-secret
  namespace: vsecm-system
type: Opaque
stringData:
  data: {{ .Values.initCommand.command | quote }}
{{- end }}
