apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterFederatedTrustDomain
metadata:
  name: cluster2
spec:
  trustDomain: cluster2.demo
  bundleEndpointURL: https://10.0.0.70:8443
  bundleEndpointProfile:
    type: https_spiffe
    endpointSPIFFEID: spiffe://cluster2.demo/spire/server
  trustDomainBundle: |-
    {
    }
