# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

# Default values for sentinel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

livenessPort: 8081

environments:
 - name: SPIFFE_ENDPOINT_SOCKET
   value: "unix:///spire-agent-socket/agent.sock"
 - name: VSECM_LOG_LEVEL
   value: "7"
 - name: VSECM_PROBE_LIVENESS_PORT
   value: ":8081"
 - name: VSECM_SAFE_ENDPOINT_URL
   value: "https://vsecm-safe.vsecm-system.svc.cluster.local:8443/"
 - name: VSECM_SAFE_SPIFFEID_PREFIX
   value: "spiffe://vsecm.com/workload/vsecm-safe/ns/vsecm-system/sa/vsecm-safe/n/"
 - name: VSECM_SAFE_TLS_PORT
   value: ":8443"
 - name: VSECM_SENTINEL_INIT_COMMAND_PATH
   value: "/opt/vsecm-sentinel/init/data"
 - name: VSECM_SENTINEL_LOGGER_URL
   value: "localhost:50051"
 - name: VSECM_SENTINEL_SECRET_GENERATION_PREFIX
   value: "gen:"
 - name: VSECM_SENTINEL_SPIFFEID_PREFIX
   value: "spiffe://vsecm.com/workload/vsecm-sentinel/ns/vsecm-system/sa/vsecm-sentinel/n/"
 - name: VSECM_SENTINEL_OIDC_PROVIDER_BASE_URL
   value: "http://0.0.0.0:8080/auth/realms/XXXXX/protocol/openid-connect/token/introspect"
 - name: VSECM_SENTINEL_ENABLE_OIDC_RESOURCE_SERVER
   value: "false"

# Override it with an image pull secret that you need as follows:
# imagePullSecrets:
#  - name: my-registry-secret
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "vsecm-sentinel"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  # These are default requests that can be used as a starting point.
  # Of course, benchmark your production system to determine the actual
  # requests you need.
  requests:
    memory: "20Mi"
    cpu: "5m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

initCommand:
  enabled: true

  # Add any initialization command here, separated by a line with only "--"
  # The command stanza MUST end with a "--".
  command: |
    exit:true
    --

  #  Example:
  #  --------
  #
  #  sleep:30001
  #  --
  #  w:keycloak-admin-secret,keycloak-db-secret
  #  n:smo-app,web-app
  #  s:gen:{"username":"admin-[a-z0-9]{6}","password":"[a-zA-Z0-9]{12}"}
  #  t:{"KEYCLOAK_ADMIN_USER":"{{.username}}","KEYCLOAK_ADMIN_PASSWORD":"{{.password}}"}
  #  --
  #  w:k8s:keycloak-db-secret
  #  n:smo-app
  #  s:gen:{"username":"admin-[a-z0-9]{6}","password":"[a-zA-Z0-9]{12}"}
  #  t:{"KEYCLOAK_DB_USER":"{{.username}}","KEYCLOAK_DB_PASSWORD":"{{.password}}"}
  #  --
  #  sleep:5000
  #  --
  #  w:keycloak
  #  n:default
  #  s:trigger-init
  #  --
