apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-controller-manager-config
  namespace: {{ .Values.global.spire.namespace }}
data:
  spire-controller-manager-config.yaml: |
    apiVersion: spire.spiffe.io/v1alpha1
    kind: ControllerManagerConfig
    metrics:
      bindAddress: 127.0.0.1:8082
    healthProbe:
      bindAddress: 127.0.0.1:8083
    leaderElection:
      leaderElect: true
      resourceName: 98c9c988.spiffe.io
      resourceNamespace: {{ .Values.global.spire.namespace }}
    clusterName: vsecm-cluster
    trustDomain: vsecm.com
    ignoreNamespaces:
      - kube-system
      - kube-public
      - {{ .Values.global.spire.namespace }}
      - local-path-storage
      # - do not ignore vsecm-system!
      # - vsecm-system
      - kube-node-lease
      - kube-public
      - kubernetes-dashboard
