
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-store
  labels:
    app: edge-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-store
  template:
    metadata:
      labels:
        app: edge-store
    spec:
      volumes:
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/agent-sockets
          type: DirectoryOrCreate
      containers:
      - name: edge-store
        image: localhost:32000/edge-store:latest
        volumeMounts:
          - name: spire-agent-socket
            mountPath: /spire-agent-socket
            readOnly: true
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///spire-agent-socket/spire-agent.sock"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        imagePullPolicy: Always
