# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: v1
kind: Service
metadata:
  name: {{ include "scout.fullname" . }}
  namespace: {{ .Values.global.vsecm.namespace }}
  labels:
    {{- include "scout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.service.tlsEnabled }}
  - port: {{ .Values.service.tlsPort }}
    targetPort: {{ .Values.service.tlsPort }}
    protocol: TCP
    name: https
  {{- else }}
  - port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }}
    protocol: TCP
    name: http
  {{- end }}
  selector:
    {{- include "scout.selectorLabels" . | nindent 4 }}
