apiVersion: batch/v1
kind: Job
metadata:
  name: spire-spiffe-oidc-discovery-provider-pre-delete
  namespace: spire-server
  labels:
    helm.sh/chart: spiffe-oidc-discovery-provider-0.1.0
    app.kubernetes.io/name: spiffe-oidc-discovery-provider
    app.kubernetes.io/instance: spire
    app.kubernetes.io/version: "1.9.6"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
spec:
  template:
    metadata:
      name: spire-spiffe-oidc-discovery-provider-pre-delete
    spec:
      restartPolicy: Never
      serviceAccountName: spire-spiffe-oidc-discovery-provider-pre-delete
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsUser: 1000
      containers:
      - name: pre-delete-job
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        image: docker.io/rancher/kubectl:v1.28.0
        args:
          - delete
          - -n
          - spire-server
          - deployment
          - spire-spiffe-oidc-discovery-provider
          - --wait
