# Source: spire/templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: spire-system
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    security.openshift.io/scc.podSecurityLabelSync: "false" # !!!
---
# Source: spire/templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: spire-server
  labels:
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: restricted
    security.openshift.io/scc.podSecurityLabelSync: "false" # !!!