apiVersion: v1
kind: Pod
metadata:
  name: "spire-spiffe-oidc-discovery-provider-test-keys"
  namespace: spire-server
  labels:
    helm.sh/chart: spiffe-oidc-discovery-provider-0.1.0
    app.kubernetes.io/name: spiffe-oidc-discovery-provider
    app.kubernetes.io/instance: spire
    app.kubernetes.io/version: "1.9.6"
    app.kubernetes.io/managed-by: Helm
    release: spire
    release-namespace: spire-server
    component: test-keys
  annotations:
    "helm.sh/hook": test
spec:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 1000
    runAsUser: 1000
  serviceAccountName: spire-spiffe-oidc-discovery-provider
  initContainers:
    - name: static-busybox
      image: busybox:1.36.1-uclibc
      command:
        - sh
        - -c
        - |
          cp /bin/busybox /data/busybox
          chmod +x /data/busybox
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: data-volume
          mountPath: /data
    - name: install-step
      image: docker.io/smallstep/step-cli:0.26.1
      workingDir: /data
      command:
        - sh
        - -c
        - |
          cp /usr/local/bin/step /data/step
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: data-volume
          mountPath: /data
    - name: gettoken
      image: ghcr.io/spiffe/spire-agent:1.9.6
      command:
        - /data/busybox
        - sh
        - -c
        - |
          while true; do
            /opt/spire/bin/spire-agent api fetch jwt -audience foo -format json -socketPath /spire-agent/spire-agent.sock -timeout 5s > /data/token.svid
            [ $? -eq 0 ] && break
            sleep 1
          done
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: spire-api
          mountPath: /spire-agent
          readOnly: true
  containers:
    - name: verify-keys
      image: cgr.dev/chainguard/min-toolkit-debug:latest@sha256:d94454739d8be0239cfe93453df79c88d25d38b7a97084d81a49e9403a90d07c
      command:
        - bash
      workingDir: /data
      env:
      - name: TMPDIR
        value: /data
      args:
        - -cx
        - |
          URL=https://spire-spiffe-oidc-discovery-provider.spire-server.svc.cluster.local:443

          cat /data/token.svid
          JWT=$(cat /data/token.svid | jq -r '.[] | select(.svids) | .svids[0].svid' | xargs)
          KID=$(echo $JWT | base64 -d 2>/dev/null | jq -r '.kid')
          curl -k -s --fail-with-body "${URL}"/keys | jq '.keys[] | select(.kid == "'${KID}'")' > public.pem
          echo $JWT | /data/step crypto jwt verify --key=public.pem --alg=RS256 --subtle
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
      - mountPath: /data
        name: data-volume
  restartPolicy: Never
  volumes:
  - csi:
      driver: csi.spiffe.io
      readOnly: true
    name: spire-api
  - name: data-volume
    emptyDir: {}
