apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spire-spiffe-oidc-discovery-provider-pre-delete
  namespace: spire-server
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["spire-spiffe-oidc-discovery-provider"]
    verbs: ["get", "delete"]
