kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spire-spiffe-oidc-discovery-provider-pre-delete
  namespace: spire-server
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
subjects:
  - kind: ServiceAccount
    name: spire-spiffe-oidc-discovery-provider-pre-delete
    namespace: spire-server
roleRef:
  kind: Role
  name: spire-spiffe-oidc-discovery-provider-pre-delete
  apiGroup: rbac.authorization.k8s.io
