# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vsecm-secret-readwriter-binding
subjects:
  - kind: ServiceAccount
    name: vsecm-safe
    namespace: {{ .Values.global.vsecm.namespace }}
roleRef:
  kind: ClusterRole
  name: vsecm-secret-readwriter
  apiGroup: rbac.authorization.k8s.io

##
#
# Alternatively, for a tighter security, you can define a `RoleBinding`
# instead of a `ClusterRoleBinding`. It will be more secure, yet harder to
# maintain. See the discussion about above `Role`s and `RoleBinding`s.
#
#   apiVersion: rbac.authorization.k8s.io/v1
#   kind: RoleBinding
#   metadata:
#     name: vsecm-secret-readwriter-binding
#     namespace: {{ .Values.global.vsecm.namespace }}
#   subjects:
#     - kind: ServiceAccount
#       name: vsecm-safe
#       namespace: {{ .Values.global.vsecm.namespace }}
#   roleRef:
#     kind: Role
#     name: vsecm-secret-readwriter
#     apiGroup: rbac.authorization.k8s.io
#
##
