
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spire-agent
  labels:
    helm.sh/chart: spire-0.26.1
    app.kubernetes.io/name: spire
    app.kubernetes.io/instance: vsecm
    app.kubernetes.io/version: "0.26.1"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: spire-agent
    namespace: spire-system
roleRef:
  kind: ClusterRole
  name: spire-agent
  apiGroup: rbac.authorization.k8s.io
