
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent
  namespace: spire-system
  labels:
    helm.sh/chart: spire-0.26.1
    app.kubernetes.io/name: spire
    app.kubernetes.io/instance: vsecm
    app.kubernetes.io/version: "0.26.1"
    app.kubernetes.io/managed-by: Helm
data:
  agent.conf: |
    {
      "agent": {
        "data_dir": "/run/spire",
        "log_level": "DEBUG",
        "server_address": "spire-server.spire-server.svc.cluster.local",
        "server_port": "443",
        "socket_path": "/tmp/spire-agent/public/spire-agent.sock",
        "trust_bundle_path": "/run/spire/bundle/bundle.crt",
        "trust_domain": "vsecm.com"
      },
      "health_checks": {
        "bind_address": "0.0.0.0",
        "bind_port": "9982",
        "listener_enabled": true,
        "live_path": "/live",
        "ready_path": "/ready"
      },
      "plugins": {
        "NodeAttestor": [
          {
            "k8s_psat": {
              "plugin_data": {
                "cluster": "vsecm-cluster"
              }
            }
          }
        ],
        "KeyManager": [
          {
            "memory": {
              "plugin_data": null
            }
          }
        ],
        "WorkloadAttestor": [
          {
            "k8s": {
              "plugin_data": {
                "disable_container_selectors": false,
                "skip_kubelet_verification": true,
                "use_new_container_locator": false,
                "verbose_container_locator_logs": false
              }
            }
          }
        ]
      }
    }
