
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-bundle
  namespace: spire-system
  labels:
    helm.sh/chart: spire-0.26.1
    app.kubernetes.io/name: spire
    app.kubernetes.io/instance: vsecm
    app.kubernetes.io/version: "0.26.1"
    app.kubernetes.io/managed-by: Helm
