
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server
  namespace: spire-server
  labels:
    helm.sh/chart: spire-0.26.1
    app.kubernetes.io/name: spire
    app.kubernetes.io/instance: vsecm
    app.kubernetes.io/version: "0.26.1"
    app.kubernetes.io/managed-by: Helm
data:
  server.conf: |
    {
      "server": {
        "audit_log_enabled": true,
        "bind_address": "0.0.0.0",
        "bind_port": 8081,
        "trust_domain": "vsecm.com",
        "data_dir": "/run/spire/data",
        "log_level": "DEBUG",
        "ca_key_type": "rsa-2048",
        "ca_subject": [
          {
            "common_name": "vsecm.com",
            "country": [
                "US"
            ],
            "organization": [
              "vsecm.com"
            ]
          }
        ]
      },
      "health_checks": {
        "bind_address": "0.0.0.0",
        "bind_port": "8080",
        "listener_enabled": true,
        "live_path": "/live",
        "ready_path": "/ready"
      },
      "plugins": {
        "DataStore": [
          {
            "sql": {
              "plugin_data": {
                "database_type": "sqlite3",
                "connection_string": "/run/spire/data/datastore.sqlite3"
              }
            }
          }
        ],
        "NodeAttestor": [
          {
            "k8s_psat": {
              "plugin_data": {
                "clusters": [
                  {
                    "vsecm-cluster": {
                      "allowed_node_label_keys": [],
                      "allowed_pod_label_keys": [],
                      "audience": [
                        "spire-server"
                      ],
                      "service_account_allow_list": [
                        "spire-system:spire-agent"
                      ]
                    }
                  }
                ]
              }
            }
          }
        ],
        "KeyManager": [
          {
            "disk": {
              "plugin_data": {
                "keys_path": "/run/spire/data/keys.json"
              }
            }
          }
        ],
        "Notifier": [
          {
            "k8sbundle": {
              "plugin_data": {
                "config_map": "spire-bundle",
                "namespace": "spire-system"
              }
            }
          }
        ]
      }
    }
