
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spire-bundle
  namespace: spire-system
  labels:
    helm.sh/chart: spire-0.26.1
    app.kubernetes.io/name: spire
    app.kubernetes.io/instance: vsecm
    app.kubernetes.io/version: "0.26.1"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: spire-server
    namespace: spire-server
roleRef:
  kind: Role
  name: spire-bundle
  apiGroup: rbac.authorization.k8s.io
