
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spire-controller-manager-leader-election
  namespace: spire-server
  labels:
    helm.sh/chart: spire-0.26.1
    app.kubernetes.io/name: spire
    app.kubernetes.io/instance: vsecm
    app.kubernetes.io/version: "0.26.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spire-controller-manager-leader-election
subjects:
  - kind: ServiceAccount
    name: spire-server
    namespace: spire-server
