# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: {{ include "sentinel.fullname" . }}
spec:
  spiffeIDTemplate: "spiffe://vsecm.com\
    /workload/{{ include "sentinel.fullname" . }}\
    /ns/{{`{{ .PodMeta.Namespace }}`}}\
    /sa/{{`{{ .PodSpec.ServiceAccountName }}`}}\
    /n/{{`{{ .PodMeta.Name }}`}}"
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sentinel.fullname" . }}
      app.kubernetes.io/part-of: {{ .Values.global.vsecm.namespace }}
  workloadSelectorTemplates:
    - "k8s:ns:{{ .Values.global.vsecm.namespace }}"
    - "k8s:sa:{{ include "sentinel.serviceAccountName" . }}"
