# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: default
  labels:
    app.kubernetes.io/name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example
    spec:
      serviceAccountName: example
      containers:
      - name: main
        image: vsecm/example-using-sidecar:0.20.0
        volumeMounts:
        # `main` shares this volume with `sidecar`.
        - mountPath: /opt/vsecm
          name: vsecm-secrets-volume
      - name: sidecar
        image: vsecm/vsecm-ist-sidecar:0.20.0
        volumeMounts:
        # /opt/vsecm/secrets.json is the place the secrets will be at.
        - mountPath: /opt/vsecm
          name: vsecm-secrets-volume
        # Volume mount for SPIRE unix domain socket.
        - name: spire-agent-socket
          mountPath: /spire-agent-socket
          readOnly: true
        #
        # You can configure this workload by providing environment variables.
        #
        # See https://vsecm.com/configuration for more information about
        # these environment variables.
        #
        # When you don’t explicitly provide env vars here, VMware Secrets Manager
        # Safe will assume the default values outlined in the given link above.
        #
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///spire-agent-socket/agent.sock"
        - name: VSECM_LOG_LEVEL
          value: "7"
        - name: VSECM_WORKLOAD_SVID_PREFIX
          value: "spiffe://vsecm.com/workload/"
        - name: VSECM_SAFE_SVID_PREFIX
          value: "spiffe://vsecm.com/workload/vsecm-safe/ns/vsecm-system/sa/vsecm-safe/n/"
        - name: VSECM_SIDECAR_POLL_INTERVAL
          value: "5000"
        - name: VSECM_SIDECAR_MAX_POLL_INTERVAL
          value: "300000"
        - name: VSECM_SIDECAR_EXPONENTIAL_BACKOFF_MULTIPLIER
          value: "2"
        - name: VSECM_SIDECAR_SUCCESS_THRESHOLD
          value: "3"
        - name: VSECM_SIDECAR_ERROR_THRESHOLD
          value: "2"
      volumes:
      # A memory-backed volume is recommended (but not required) to keep
      # the secrets. The secrets can be stored in any kind of volume.
      - name: vsecm-secrets-volume
        emptyDir:
          medium: Memory
      # Using SPIFFE CSI Driver to bind to the SPIRE Agent Socket
      # ref: https://github.com/spiffe/spiffe-csi
      - name: spire-agent-socket
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
