/*
|    Protect your secrets, protect your sensitive data.
:    Explore VMware Secrets Manager docs at https://vsecm.com/
</
<>/  keep your secrets... secret
>/
<>/' Copyright 2023-present VMware Secrets Manager contributors.
>/'  SPDX-License-Identifier: BSD-2-Clause
*/

package val

import "strings"

const TimeNow = "now"
const TimeNever = "never"

const BlankRootKey = "{}"

const Ok = "OK"
const NotOk = "NOK!"

// JsonEmpty is a constant string representing an empty value.
// This value is generated by the go templating engine
// when a key-value pair has no value. Don't change this value.
const JsonEmpty = "<no value>"

// Never returns true if the string is "never".
func Never(s string) bool {
	return TimeNever == strings.ToLower(strings.TrimSpace(s))
}

// True returns true if the string is "true".
func True(s string) bool {
	return "true" == strings.ToLower(strings.TrimSpace(s))
}
