
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent
  namespace: spire-system
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire"
      log_level = "DEBUG"
      server_address = "spire-server.spire-server.svc.cluster.local"
      server_port = "8081"
      socket_path = "/run/spire/sockets/agent.sock"
      trust_bundle_path = "/run/spire/bundle/bundle.crt"
      trust_domain = "vsecm.com"
    }

    health_checks {
      bind_address = "0.0.0.0"
      bind_port = "9982"
      listener_enabled = true
      live_path = "/live"
      ready_path = "/ready"
    }

    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "vsecm-cluster"
        }
      }

      KeyManager "memory" {
        plugin_data {
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
          skip_kubelet_verification = true
        }
      }
    }
