
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-controller-manager-config
  namespace: spire-server
data:
  spire-controller-manager-config.yaml: |
    apiVersion: spire.spiffe.io/v1alpha1
    kind: ControllerManagerConfig
    metrics:
      bindAddress: 127.0.0.1:8082
    health:
      healthProbeBindAddress: 0.0.0.0:8083
    leaderElection:
      leaderElect: true
      resourceName: 98c9c988.spiffe.io
      resourceNamespace: spire-server
    clusterName: vsecm-cluster
    trustDomain: vsecm.com
    ignoreNamespaces:
      - kube-system
      - kube-public
      - spire-system
      - spire-server
      - local-path-storage
      - kube-node-lease
      - kube-public
      - kubernetes-dashboard
      - openshift-cluster-node-tuning-operator
      - openshift-cluster-samples-operator
      - openshift-cluster-storage-operator
      - openshift-console-operator
      - openshift-console
      - openshift-dns
      - openshift-dns-operator
      - openshift-image-registry
      - openshift-ingress
      - openshift-kube-storage-version-migrator
      - openshift-kube-storage-version-migrator-operator
      - openshift-kube-proxy
      - openshift-marketplace
      - openshift-monitoring
      - openshift-multus
      - openshift-network-diagnostics
      - openshift-network-operator
      - openshift-operator-lifecycle-manager
      - openshift-roks-metrics
      - openshift-service-ca-operator
      - openshift-service-ca
      - ibm-odf-validation-webhook
      - ibm-system
