
apiVersion: v1
kind: Service
metadata:
  name: spire-server-bundle-endpoint
  namespace: spire-server
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 8443
      protocol: TCP
  selector:
    app: spire-server
