# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

# !!!
# !!! Keeping the `vsecm-safe-age-key` Secret secure is critical
# !!! for production deployments. See the following link for details:
# !!!
# !!! https://vsecm.com/production/
# !!!
apiVersion: v1
kind: Secret
metadata:
  name: vsecm-safe-age-key
  namespace: vsecm-system
type: Opaque
data:
  # '{}' (e30=) is a special placeholder to tell Safe that the Secret
  # is not initialized. DO NOT remove or change it.
  KEY_TXT: "e30="
