# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rootKeySecretName }}
  namespace: {{ .Values.global.vsecm.namespace }}
  labels:
    {{- include "safe.labels" . | nindent 4 }}
    app.kubernetes.io/operated-by: vsecm
  annotations:
    kubernetes.io/service-account.name: {{ include "safe.serviceAccountName" . }}
type: Opaque
data:
  # '{}' (e30=) is a special placeholder to tell Safe that the Secret
  # is not initialized. DO NOT remove or change it.
  KEY_TXT: "e30="
