# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

{{- if .Values.initCommand.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: vsecm-sentinel-init-secret
  namespace: vsecm-system
type: Opaque
stringData:
  data: {{ .Values.initCommand.command | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vsecm-sentinel-init-tombstone
  namespace: vsecm-system
type: Opaque
stringData:
  init: "not-initialized"
{{- end }}
