# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: control-plane-server
spec:
  federatesWith: ["mephisto.vsecm.com","baal.vsecm.com","azmodan.vsecm.com"]
  className: "vsecm"
  spiffeIDTemplate: "spiffe://diablo.vsecm.com\
    /workload/diablo-control-plane-server\
    /ns/{{ .PodMeta.Namespace }}\
    /sa/{{ .PodSpec.ServiceAccountName }}\
    /n/{{ .PodMeta.Name }}"
  podSelector:
    matchLabels:
      app: control-plane-server
