# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: v1
kind: Service
metadata:
  name: control-plane-service
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.211.55.112
spec:
  type: LoadBalancer
  selector:
    app: control-plane-server
  ports:
    - port: 443
      targetPort: 443
