apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coke-admin-credentials
  namespace: coke-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vsecm-scout
    kind: ClusterSecretStore
  target:
    name: admin-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
      templateFrom:
      - target: Labels
        literal: "managed-by: {{ .password }}"
      - target: Annotations
        literal: "inject-sidecar: {{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: "key=coca-cola.cluster-001&path=namespaces.cokeSystem.secrets.adminCredentials.value"