
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: "csi.spiffe.io"
  annotations:
    "helm.sh/hook": pre-install
  labels:
    helm.sh/chart: spire-0.26.1
    app.kubernetes.io/name: spire
    app.kubernetes.io/instance: vsecm
    app.kubernetes.io/version: "0.26.1"
    app.kubernetes.io/managed-by: Helm
spec:
  attachRequired: false

  podInfoOnMount: true

  fsGroupPolicy: None

  volumeLifecycleModes: # added in Kubernetes 1.16, this field is beta
    - Ephemeral
