# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

apiVersion: v1
kind: ConfigMap
metadata:
  name: trust-bundle
  namespace: spire-system
data:
  vsecm-002-bundle.json: |
    {
      "keys": [
        {
          "use": "x509-svid",
          "kty": "EC",
          "crv": "P-256",
          "x": "--redacted--",
          "y": "--redacted--",
          "x5c": [
            "--redacted--"
          ]
        },
        {
          "use": "jwt-svid",
          "kty": "EC",
          "kid": "--redacted--",
          "crv": "P-256",
          "x": "--redacted--",
          "y": "--redacted--"
        }
      ],
      "spiffe_sequence": 1
    }
