# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware, Inc.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

# Default values for safe.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

livenessPort: 8081
readynessPort: 8082
ageKeySecretName: &ageKeySecretName vsecm-safe-age-key

environments:
 - name: SPIFFE_ENDPOINT_SOCKET
   value: "unix:///spire-agent-socket/agent.sock"
 - name: VSECM_LOG_LEVEL
   value: "7"
 - name: VSECM_WORKLOAD_SVID_PREFIX
   value: "spiffe://vsecm.com/workload/"
 - name: VSECM_SAFE_DATA_PATH
   value: "/data"
 - name:  VSECM_CRYPTO_KEY_NAME
   value: *ageKeySecretName
 - name: VSECM_CRYPTO_KEY_PATH
   value: "/key/key.txt"
 - name: VSECM_SAFE_MANUAL_KEY_INPUT
   value: "false"
 - name: VSECM_SAFE_SECRET_NAME_PREFIX
   value: "VSECM-secret-"
 - name: VSECM_SAFE_TLS_PORT
   value: ":8443"
 - name: VSECM_SAFE_SECRET_BUFFER_SIZE
   value: "10"
 - name: VSECM_SAFE_K8S_SECRET_BUFFER_SIZE
   value: "10"
 - name: VSECM_SAFE_SECRET_DELETE_BUFFER_SIZE
   value: "10"
 - name: VSECM_SAFE_K8S_SECRET_DELETE_BUFFER_SIZE
   value: "10"
 - name: VSECM_SAFE_USE_KUBERNETES_SECRETS
   value: "false"
 - name: VSECM_SAFE_BOOTSTRAP_TIMEOUT
   value: "30000"
 - name: VSECM_SAFE_FIPS_COMPLIANT
   value: "false"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8443
  targetPort: 8443

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
