apiVersion: v1
kind: Service
metadata:
  name: vsecm-scout
  namespace: vsecm-system
spec:
  type: LoadBalancer
  selector:
    app: vsecm-scout
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
