apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vsecm-scout
spec:
  provider:
    webhook:
      url: "http://vsecm-scout.default.svc.cluster.local:80/webhook?key={{ .remoteRef.key }}"
      method: GET
      result:
        jsonPath: "$"