# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets... secret
# >/
# <>/' Copyright 2023-present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

# Role for the SPIRE server
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spire-server-role
  namespace: {{ .Values.global.spire.namespace }}
rules:
  # allow "get" access to pods (to resolve selectors for PSAT attestation)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
    # allow access to "get" and "patch" the spire-bundle ConfigMap (for SPIRE
    # agent bootstrapping, see the spire-bundle ConfigMap below)
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["spire-bundle"]
    verbs: ["get", "patch"]
